package com.IRS.optaplanner;

import javax.persistence.Table;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@Table(name="paper")
public class Paper implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "PAPER_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PAPER_ID_SEQ", name = "PAPER_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("authors")
	@javax.persistence.Column(name = "authors")
	private java.lang.String authors;

	@org.kie.api.definition.type.Label("title")
	@javax.persistence.Column(name = "title")
	private java.lang.String title;

	@org.kie.api.definition.type.Label("category")
	@javax.persistence.Column(name = "category")
	private java.lang.String category;

	@org.kie.api.definition.type.Label("date")
	@javax.persistence.Column(name = "date")
	private java.lang.String date;

	@org.kie.api.definition.type.Label("source")
	@javax.persistence.Column(name = "source")
	private java.lang.String source;
	
	@org.kie.api.definition.type.Label("keyword")
	@javax.persistence.Column(name = "keyword")
	private java.lang.String keyword;
	
	@org.kie.api.definition.type.Label("paperid")
	@javax.persistence.Column(name = "paperid")
	private java.lang.String paperid;
	

	public Paper() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getAuthors() {
		return this.authors;
	}

	public void setAuthors(java.lang.String authors) {
		this.authors = authors;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.lang.String getDate() {
		return this.date;
	}

	public void setDate(java.lang.String date) {
		this.date = date;
	}

	public java.lang.String getSource() {
		return this.source;
	}

	public void setSource(java.lang.String source) {
		this.source = source;
	}
	
	

	public java.lang.String getKeyword() {
		return keyword;
	}

	public void setKeyword(java.lang.String keyword) {
		this.keyword = keyword;
	}

	public java.lang.String getPaperid() {
		return paperid;
	}

	public void setPaperid(java.lang.String paperid) {
		this.paperid = paperid;
	}

	public Paper(Long id, String authors, String title, String category, String date, String source, String keyword,
			String paperid) {
		super();
		this.id = id;
		this.authors = authors;
		this.title = title;
		this.category = category;
		this.date = date;
		this.source = source;
		this.keyword = keyword;
		this.paperid = paperid;
	}
	
	
	
	
	

}