package com.IRS.optaplanner;

import org.optaplanner.core.api.domain.constraintweight.ConstraintConfigurationProvider;
import org.optaplanner.core.api.domain.solution.drools.ProblemFactCollectionProperty;;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution
@javax.xml.bind.annotation.XmlRootElement
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class Solution implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.annotation.Generated(value = {"org.optaplanner.workbench.screens.domaineditor.client.widgets.planner.PlannerDataObjectEditor"})
	@javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(value = org.optaplanner.persistence.jaxb.api.score.buildin.hardsoft.HardSoftScoreJaxbXmlAdapter.class)
	@org.kie.api.definition.type.Label(value = "Generated Planner score field")
	
	@org.optaplanner.core.api.domain.solution.PlanningScore
	private org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score;
	
	@org.optaplanner.core.api.domain.solution.PlanningEntityCollectionProperty
	@org.kie.api.definition.type.Label(value = "UserList")
	private java.util.List<com.IRS.optaplanner.User> userList;
	
	@org.optaplanner.core.api.domain.valuerange.ValueRangeProvider(id = "paperRange")
	@org.kie.api.definition.type.Label(value = "PaperList")
	@ProblemFactCollectionProperty
	private java.util.List<com.IRS.optaplanner.Paper> paperList;
	
	@ConstraintConfigurationProvider
	private PaperConstraintConfiguration constraintConfiguration;

	public Solution() {
	}

	public org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore getScore() {
		return this.score;
	}

	public void setScore(
			org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score) {
		this.score = score;
	}

	public java.util.List<com.IRS.optaplanner.User> getUserList() {
		return this.userList;
	}

	public void setUserList(java.util.List<com.IRS.optaplanner.User> userList) {
		this.userList = userList;
	}

	public java.util.List<com.IRS.optaplanner.Paper> getPaperList() {
		return this.paperList;
	}

	public void setPaperList(
			java.util.List<com.IRS.optaplanner.Paper> paperList) {
		this.paperList = paperList;
	}
	

	public PaperConstraintConfiguration getConstraintConfiguration() {
		return constraintConfiguration;
	}

	public void setConstraintConfiguration(PaperConstraintConfiguration constraintConfiguration) {
		this.constraintConfiguration = constraintConfiguration;
	}

	public Solution(
			org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score,
			java.util.List<com.IRS.optaplanner.User> userList,
			java.util.List<com.IRS.optaplanner.Paper> paperList) {
		this.score = score;
		this.userList = userList;
		this.paperList = paperList;
	}
	
	public Solution(
			java.util.List<com.IRS.optaplanner.User> userList,
			java.util.List<com.IRS.optaplanner.Paper> paperList,
			PaperConstraintConfiguration constraintConfiguration) {
		this.constraintConfiguration = constraintConfiguration;
		this.userList = userList;
		this.paperList = paperList;
	}

}