package com.IRS.optaplanner;

import org.optaplanner.core.api.domain.variable.PlanningVariable;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class User implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("requiredAuthors")
	private java.lang.String requiredAuthors = "";
	@org.kie.api.definition.type.Label("requiredCategory")
	private java.lang.String requiredCategory = "";
	@org.kie.api.definition.type.Label("requiredDate")
	private java.lang.String requiredDate = "";
	@org.kie.api.definition.type.Label("requiredTitle")
	private java.lang.String requiredTitle = "";

	@org.kie.api.definition.type.Label("requiredSource")
	private java.lang.String requiredSource = "";

	@PlanningVariable(valueRangeProviderRefs = {"paperRange"})
	@org.kie.api.definition.type.Label("Paper")
	private com.IRS.optaplanner.Paper paper;

	@org.kie.api.definition.type.Label("isRule")
	private boolean isRule;

	@org.kie.api.definition.type.Label("authorsWeight")
	private java.lang.Integer authorsWeight = 1;

	@org.kie.api.definition.type.Label("categoryWeight")
	private java.lang.Integer categoryWeight = 1;

	@org.kie.api.definition.type.Label("dateWeight")
	private java.lang.Integer dateWeight = 1;

	@org.kie.api.definition.type.Label("sourceWeight")
	private java.lang.Integer sourceWeight = 1;

	@org.kie.api.definition.type.Label(value = "titleWeight")
	private java.lang.Integer titleWeight = 1;

	public User() {
	}

	public java.lang.String getRequiredAuthors() {
		return this.requiredAuthors;
	}

	public void setRequiredAuthors(java.lang.String requiredAuthors) {
		this.requiredAuthors = requiredAuthors;
	}

	public java.lang.String getRequiredCategory() {
		return this.requiredCategory;
	}

	public void setRequiredCategory(java.lang.String requiredCategory) {
		this.requiredCategory = requiredCategory;
	}

	public java.lang.String getRequiredDate() {
		return this.requiredDate;
	}

	public void setRequiredDate(java.lang.String requiredDate) {
		this.requiredDate = requiredDate;
	}

	public java.lang.String getRequiredTitle() {
		return this.requiredTitle;
	}

	public void setRequiredTitle(java.lang.String requiredTitle) {
		this.requiredTitle = requiredTitle;
	}

	public java.lang.String getRequiredSource() {
		return this.requiredSource;
	}

	public void setRequiredSource(java.lang.String requiredSource) {
		this.requiredSource = requiredSource;
	}
	

	public com.IRS.optaplanner.Paper getPaper() {
		return this.paper;
	}

	public void setPaper(com.IRS.optaplanner.Paper paper) {
		this.paper = paper;
	}

	public boolean isIsRule() {
		return this.isRule;
	}

	public void setIsRule(boolean isRule) {
		this.isRule = isRule;
	}

	public java.lang.Integer getAuthorsWeight() {
		return this.authorsWeight;
	}

	public void setAuthorsWeight(java.lang.Integer authorsWeight) {
		this.authorsWeight = authorsWeight;
	}

	public java.lang.Integer getCategoryWeight() {
		return this.categoryWeight;
	}

	public void setCategoryWeight(java.lang.Integer categoryWeight) {
		this.categoryWeight = categoryWeight;
	}

	public java.lang.Integer getDateWeight() {
		return this.dateWeight;
	}

	public void setDateWeight(java.lang.Integer dateWeight) {
		this.dateWeight = dateWeight;
	}

	public java.lang.Integer getSourceWeight() {
		return this.sourceWeight;
	}

	public void setSourceWeight(java.lang.Integer sourceWeight) {
		this.sourceWeight = sourceWeight;
	}

	public java.lang.Integer getTitleWeight() {
		return this.titleWeight;
	}

	public void setTitleWeight(java.lang.Integer titleWeight) {
		this.titleWeight = titleWeight;
	}

	
	public User(java.lang.String requiredAuthors,
			java.lang.String requiredCategory, java.lang.String requiredDate,
			java.lang.String requiredTitle, java.lang.String requiredSource,
			 boolean isRule,
			java.lang.Integer authorsWeight, java.lang.Integer categoryWeight,
			java.lang.Integer dateWeight, java.lang.Integer sourceWeight,
			java.lang.Integer titleWeight) {
		this.requiredAuthors = requiredAuthors;
		this.requiredCategory = requiredCategory;
		this.requiredDate = requiredDate;
		this.requiredTitle = requiredTitle;
		this.requiredSource = requiredSource;
		this.isRule = isRule;
		this.authorsWeight = authorsWeight;
		this.categoryWeight = categoryWeight;
		this.dateWeight = dateWeight;
		this.sourceWeight = sourceWeight;
		this.titleWeight = titleWeight;
	}

}